### ISSUE TITLE
duplicate symbols

### ISSUE THREAD

**Issue by revolunet** [phonegap/phonegap-webview-ios#8] opened 2016-05-16 17:12 UTC
Hi, thanks for the repo and article 👍 

For some reason, i have the following infamous error when following the [tuto](http://docs.phonegap.com/develop/1-embed-webview/ios/) when building the app : 
`duplicate symbols for architecture x86_64`

when removing plugin-file\* and capture plugin from Podfile and linker flags it builds OK, so i suspect something with cordova-plugin-file

any idea ?

``` sh
Ld /Users/juju/Library/Developer/Xcode/DerivedData/cordovaview3-aurulykhwmgczvfjdyilqzbcycow/Build/Products/Debug-iphonesimulator/cordovaview3.app/cordovaview3 normal x86_64
    cd /Users/juju/Documents/projects/xxx/cordovaview3
    export IPHONEOS_DEPLOYMENT_TARGET=8.0
    export PATH="/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/usr/bin:/Applications/Xcode.app/Contents/Developer/usr/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin"
    /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang -arch x86_64 -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator9.3.sdk -L/Users/juju/Library/Developer/Xcode/DerivedData/cordovaview3-aurulykhwmgczvfjdyilqzbcycow/Build/Products/Debug-iphonesimulator -L/Users/juju/Library/Developer/Xcode/DerivedData/cordovaview3-aurulykhwmgczvfjdyilqzbcycow/Build/Products/Debug-iphonesimulator/Cordova -L/Users/juju/Library/Developer/Xcode/DerivedData/cordovaview3-aurulykhwmgczvfjdyilqzbcycow/Build/Products/Debug-iphonesimulator/CordovaPlugin-console -L/Users/juju/Library/Developer/Xcode/DerivedData/cordovaview3-aurulykhwmgczvfjdyilqzbcycow/Build/Products/Debug-iphonesimulator/cordova-plugin-camera -L/Users/juju/Library/Developer/Xcode/DerivedData/cordovaview3-aurulykhwmgczvfjdyilqzbcycow/Build/Products/Debug-iphonesimulator/cordova-plugin-contacts -L/Users/juju/Library/Developer/Xcode/DerivedData/cordovaview3-aurulykhwmgczvfjdyilqzbcycow/Build/Products/Debug-iphonesimulator/cordova-plugin-device -L/Users/juju/Library/Developer/Xcode/DerivedData/cordovaview3-aurulykhwmgczvfjdyilqzbcycow/Build/Products/Debug-iphonesimulator/cordova-plugin-device-motion -L/Users/juju/Library/Developer/Xcode/DerivedData/cordovaview3-aurulykhwmgczvfjdyilqzbcycow/Build/Products/Debug-iphonesimulator/cordova-plugin-device-orientation -L/Users/juju/Library/Developer/Xcode/DerivedData/cordovaview3-aurulykhwmgczvfjdyilqzbcycow/Build/Products/Debug-iphonesimulator/cordova-plugin-file -L/Users/juju/Library/Developer/Xcode/DerivedData/cordovaview3-aurulykhwmgczvfjdyilqzbcycow/Build/Products/Debug-iphonesimulator/cordova-plugin-file-transfer -L/Users/juju/Library/Developer/Xcode/DerivedData/cordovaview3-aurulykhwmgczvfjdyilqzbcycow/Build/Products/Debug-iphonesimulator/cordova-plugin-geolocation -L/Users/juju/Library/Developer/Xcode/DerivedData/cordovaview3-aurulykhwmgczvfjdyilqzbcycow/Build/Products/Debug-iphonesimulator/cordova-plugin-globalization -L/Users/juju/Library/Developer/Xcode/DerivedData/cordovaview3-aurulykhwmgczvfjdyilqzbcycow/Build/Products/Debug-iphonesimulator/cordova-plugin-inappbrowser -L/Users/juju/Library/Developer/Xcode/DerivedData/cordovaview3-aurulykhwmgczvfjdyilqzbcycow/Build/Products/Debug-iphonesimulator/cordova-plugin-media-capture -L/Users/juju/Library/Developer/Xcode/DerivedData/cordovaview3-aurulykhwmgczvfjdyilqzbcycow/Build/Products/Debug-iphonesimulator/cordova-plugin-network-information -L/Users/juju/Library/Developer/Xcode/DerivedData/cordovaview3-aurulykhwmgczvfjdyilqzbcycow/Build/Products/Debug-iphonesimulator/cordova-plugin-splashscreen -L/Users/juju/Library/Developer/Xcode/DerivedData/cordovaview3-aurulykhwmgczvfjdyilqzbcycow/Build/Products/Debug-iphonesimulator/cordova-plugin-statusbar -L/Users/juju/Library/Developer/Xcode/DerivedData/cordovaview3-aurulykhwmgczvfjdyilqzbcycow/Build/Products/Debug-iphonesimulator/cordova-plugin-vibration -F/Users/juju/Library/Developer/Xcode/DerivedData/cordovaview3-aurulykhwmgczvfjdyilqzbcycow/Build/Products/Debug-iphonesimulator -filelist /Users/juju/Library/Developer/Xcode/DerivedData/cordovaview3-aurulykhwmgczvfjdyilqzbcycow/Build/Intermediates/cordovaview3.build/Debug-iphonesimulator/cordovaview3.build/Objects-normal/x86_64/cordovaview3.LinkFileList -Xlinker -rpath -Xlinker @executable_path/Frameworks -mios-simulator-version-min=8.0 -Xlinker -no_deduplicate -Xlinker -objc_abi_version -Xlinker 2 -ObjC -lCordova -lCordovaPlugin-console -lcordova-plugin-camera -lcordova-plugin-contacts -lcordova-plugin-device -lcordova-plugin-device-motion -lcordova-plugin-device-orientation -lcordova-plugin-file -lcordova-plugin-file-transfer -lcordova-plugin-geolocation -lcordova-plugin-globalization -lcordova-plugin-inappbrowser -lcordova-plugin-media-capture -lcordova-plugin-network-information -lcordova-plugin-splashscreen -lcordova-plugin-statusbar -lcordova-plugin-vibration -framework AVFoundation -framework AssetsLibrary -framework CoreGraphics -framework CoreLocation -framework CoreMedia -framework MobileCoreServices -weak_framework ImageIO -lCordova -lCordovaPlugin-console -lcordova-plugin-camera -lcordova-plugin-contacts -lcordova-plugin-device -lcordova-plugin-device-motion -lcordova-plugin-device-orientation -lcordova-plugin-file -lcordova-plugin-file-transfer -lcordova-plugin-geolocation -lcordova-plugin-globalization -lcordova-plugin-inappbrowser -lcordova-plugin-media-capture -lcordova-plugin-network-information -lcordova-plugin-splashscreen -lcordova-plugin-statusbar -lcordova-plugin-vibration -framework AVFoundation -framework AssetsLibrary -framework CoreGraphics -framework CoreLocation -framework CoreMedia -framework MobileCoreServices -weak_framework ImageIO -fobjc-arc -fobjc-link-runtime -lPods-cordovaview3 -Xlinker -dependency_info -Xlinker /Users/juju/Library/Developer/Xcode/DerivedData/cordovaview3-aurulykhwmgczvfjdyilqzbcycow/Build/Intermediates/cordovaview3.build/Debug-iphonesimulator/cordovaview3.build/Objects-normal/x86_64/cordovaview3_dependency_info.dat -o /Users/juju/Library/Developer/Xcode/DerivedData/cordovaview3-aurulykhwmgczvfjdyilqzbcycow/Build/Products/Debug-iphonesimulator/cordovaview3.app/cordovaview3

duplicate symbol _kCDVAssetsLibraryPrefix in:
    /Users/juju/Library/Developer/Xcode/DerivedData/cordovaview3-aurulykhwmgczvfjdyilqzbcycow/Build/Products/Debug-iphonesimulator/cordova-plugin-file/libcordova-plugin-file.a(CDVFile.o)
    /Users/juju/Library/Developer/Xcode/DerivedData/cordovaview3-aurulykhwmgczvfjdyilqzbcycow/Build/Products/Debug-iphonesimulator/cordova-plugin-file/libcordova-plugin-file.a(CDVAssetLibraryFilesystem.o)
duplicate symbol _kCDVFilesystemURLPrefix in:
    /Users/juju/Library/Developer/Xcode/DerivedData/cordovaview3-aurulykhwmgczvfjdyilqzbcycow/Build/Products/Debug-iphonesimulator/cordova-plugin-file/libcordova-plugin-file.a(CDVFile.o)
    /Users/juju/Library/Developer/Xcode/DerivedData/cordovaview3-aurulykhwmgczvfjdyilqzbcycow/Build/Products/Debug-iphonesimulator/cordova-plugin-file/libcordova-plugin-file.a(CDVAssetLibraryFilesystem.o)
duplicate symbol _kCDVAssetsLibraryPrefix in:
    /Users/juju/Library/Developer/Xcode/DerivedData/cordovaview3-aurulykhwmgczvfjdyilqzbcycow/Build/Products/Debug-iphonesimulator/cordova-plugin-file/libcordova-plugin-file.a(CDVFile.o)
    /Users/juju/Library/Developer/Xcode/DerivedData/cordovaview3-aurulykhwmgczvfjdyilqzbcycow/Build/Products/Debug-iphonesimulator/cordova-plugin-file/libcordova-plugin-file.a(CDVLocalFilesystem.o)
duplicate symbol _kCDVFilesystemURLPrefix in:
    /Users/juju/Library/Developer/Xcode/DerivedData/cordovaview3-aurulykhwmgczvfjdyilqzbcycow/Build/Products/Debug-iphonesimulator/cordova-plugin-file/libcordova-plugin-file.a(CDVFile.o)
    /Users/juju/Library/Developer/Xcode/DerivedData/cordovaview3-aurulykhwmgczvfjdyilqzbcycow/Build/Products/Debug-iphonesimulator/cordova-plugin-file/libcordova-plugin-file.a(CDVLocalFilesystem.o)
duplicate symbol _kCDVAssetsLibraryPrefix in:
    /Users/juju/Library/Developer/Xcode/DerivedData/cordovaview3-aurulykhwmgczvfjdyilqzbcycow/Build/Products/Debug-iphonesimulator/cordova-plugin-file/libcordova-plugin-file.a(CDVFile.o)
    /Users/juju/Library/Developer/Xcode/DerivedData/cordovaview3-aurulykhwmgczvfjdyilqzbcycow/Build/Products/Debug-iphonesimulator/cordova-plugin-file-transfer/libcordova-plugin-file-transfer.a(CDVFileTransfer.o)
duplicate symbol _kCDVFilesystemURLPrefix in:
    /Users/juju/Library/Developer/Xcode/DerivedData/cordovaview3-aurulykhwmgczvfjdyilqzbcycow/Build/Products/Debug-iphonesimulator/cordova-plugin-file/libcordova-plugin-file.a(CDVFile.o)
    /Users/juju/Library/Developer/Xcode/DerivedData/cordovaview3-aurulykhwmgczvfjdyilqzbcycow/Build/Products/Debug-iphonesimulator/cordova-plugin-file-transfer/libcordova-plugin-file-transfer.a(CDVFileTransfer.o)
duplicate symbol _kCDVAssetsLibraryPrefix in:
    /Users/juju/Library/Developer/Xcode/DerivedData/cordovaview3-aurulykhwmgczvfjdyilqzbcycow/Build/Products/Debug-iphonesimulator/cordova-plugin-file/libcordova-plugin-file.a(CDVFile.o)
    /Users/juju/Library/Developer/Xcode/DerivedData/cordovaview3-aurulykhwmgczvfjdyilqzbcycow/Build/Products/Debug-iphonesimulator/cordova-plugin-media-capture/libcordova-plugin-media-capture.a(CDVCapture.o)
duplicate symbol _kCDVFilesystemURLPrefix in:
    /Users/juju/Library/Developer/Xcode/DerivedData/cordovaview3-aurulykhwmgczvfjdyilqzbcycow/Build/Products/Debug-iphonesimulator/cordova-plugin-file/libcordova-plugin-file.a(CDVFile.o)
    /Users/juju/Library/Developer/Xcode/DerivedData/cordovaview3-aurulykhwmgczvfjdyilqzbcycow/Build/Products/Debug-iphonesimulator/cordova-plugin-media-capture/libcordova-plugin-media-capture.a(CDVCapture.o)
ld: 8 duplicate symbols for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

**Comment by revolunet** [comment] 2016-05-16 18:15
happens in both simulator (i386) and device (arm64)

**Comment by JesseHensold** [comment] 2016-05-24 20:38
I ran into this as well.  I was able to get the error to go away by removing the cordova-plugin-file, which must have class included that is causing the clash.  Unfortunately, it looks like cordova-plugin-file-transfer and cordova-plugin-media-capture seem to depend on it so I had to remove those too....

**Comment by shazron** [comment] 2016-05-25 00:28
Looks like the dependency resolution is not working well, since I think it installs duplicate source files here cc @hollyschinsky

**Comment by revolunet** [comment] 2016-05-25 10:06
I'm wondering why Cordova and cordova-plugin-\* are not declared as a dependency of the "phonegap-ios-template" podspec instead of a direct dependency in the main Podfile ?

One could add this in the `.podspec` of the "template" : 

```
s.dependency 'Cordova'
s.dependency 'cordova-plugin-wkwebview-engine'
s.dependency 'cordova-plugin-splashscreen'
s.dependency 'cordova-plugin-statusbar'
```

That way, the user who wants to install our pod, just have to add a single line to its Podfile

**Comment by hollyschinsky** [comment] 2016-05-25 20:00
Hi guys! I'm looking into this. Thanks for the info and feedback. Will post an update soon ~ Cheers, Holly

**Comment by ojunqueira** [comment] 2016-05-31 23:21
Hi Guys, I am having the same problem. Is there any solution? If I remove the cordova-plugin-file it compiles, but also does not work very well. It is weird because it worked (only) once and now it stopped working. Thanks!

duplicate symbol _kCDVAssetsLibraryPrefix in:
    /Users/otavio/Library/Developer/Xcode/DerivedData/planetario-cjyzksublnoyrpdubmcbzuepmwrs/Build/Intermediates/Pods.build/Debug-iphonesimulator/cordova-plugin-file.build/Objects-normal/x86_64/CDVAssetLibraryFilesystem.o
    /Users/otavio/Library/Developer/Xcode/DerivedData/planetario-cjyzksublnoyrpdubmcbzuepmwrs/Build/Intermediates/Pods.build/Debug-iphonesimulator/cordova-plugin-file.build/Objects-normal/x86_64/CDVFile.o
duplicate symbol _kCDVFilesystemURLPrefix in:
    /Users/otavio/Library/Developer/Xcode/DerivedData/planetario-cjyzksublnoyrpdubmcbzuepmwrs/Build/Intermediates/Pods.build/Debug-iphonesimulator/cordova-plugin-file.build/Objects-normal/x86_64/CDVAssetLibraryFilesystem.o
    /Users/otavio/Library/Developer/Xcode/DerivedData/planetario-cjyzksublnoyrpdubmcbzuepmwrs/Build/Intermediates/Pods.build/Debug-iphonesimulator/cordova-plugin-file.build/Objects-normal/x86_64/CDVFile.o
duplicate symbol _kCDVAssetsLibraryPrefix in:
    /Users/otavio/Library/Developer/Xcode/DerivedData/planetario-cjyzksublnoyrpdubmcbzuepmwrs/Build/Intermediates/Pods.build/Debug-iphonesimulator/cordova-plugin-file.build/Objects-normal/x86_64/CDVAssetLibraryFilesystem.o
    /Users/otavio/Library/Developer/Xcode/DerivedData/planetario-cjyzksublnoyrpdubmcbzuepmwrs/Build/Intermediates/Pods.build/Debug-iphonesimulator/cordova-plugin-file.build/Objects-normal/x86_64/CDVLocalFilesystem.o
duplicate symbol _kCDVFilesystemURLPrefix in:
    /Users/otavio/Library/Developer/Xcode/DerivedData/planetario-cjyzksublnoyrpdubmcbzuepmwrs/Build/Intermediates/Pods.build/Debug-iphonesimulator/cordova-plugin-file.build/Objects-normal/x86_64/CDVAssetLibraryFilesystem.o
    /Users/otavio/Library/Developer/Xcode/DerivedData/planetario-cjyzksublnoyrpdubmcbzuepmwrs/Build/Intermediates/Pods.build/Debug-iphonesimulator/cordova-plugin-file.build/Objects-normal/x86_64/CDVLocalFilesystem.o
ld: 4 duplicate symbols for architecture x86_64

**Comment by ojunqueira** [comment] 2016-06-01 21:56
Just rolled back cocoapods for version 0.39.0 and installed the pods accordingly to the ones i found in InstaSnap (https://github.com/imhotep/InstaSnap), and it started building again!

**Comment by revolunet** [comment] 2016-06-01 22:16
thanks @ojunqueira, so looks like a cocoapod > 0.39 compatibility issue

**Comment by ojunqueira** [comment] 2016-06-01 22:37
My pleasure @revolunet ! If you need more help, don't hesitate to contact me!
The pods and versions I installed were:

#CordovaLib Dependency Pod
pod 'Cordova', '3.9.1'

#Cordova Core Plugin Dependency Pod References
pod 'CordovaPlugin-console', '0.2.10'
pod 'cordova-plugin-camera', '1.2.0'
pod 'cordova-plugin-contacts', '1.1.0'
pod 'cordova-plugin-device', '1.0.1'
pod 'cordova-plugin-device-orientation', '1.0.1'
pod 'cordova-plugin-device-motion', '1.1.1'
pod 'cordova-plugin-globalization', '1.0.1'
pod 'cordova-plugin-geolocation', '0.3.10'
pod 'cordova-plugin-file', '3.0.0'
pod 'cordova-plugin-media-capture', '1.0.1'
pod 'cordova-plugin-network-information', '1.0.1'
pod 'cordova-plugin-splashscreen', '2.1.0'
pod 'cordova-plugin-inappbrowser', '1.0.1'
pod 'cordova-plugin-file-transfer', '1.3.0'
pod 'cordova-plugin-statusbar', '1.0.1'
pod 'cordova-plugin-vibration', '1.2.0'

 # The following includes the PhoneGap iOS Platform Project Template for a quick start
pod 'phonegap-ios-template', '0.1.4'

**Comment by betteray** [comment] 2016-06-02 02:42
In file "CDVFile.h",
I modify the line 23 & 24 to below and seemly build success.

extern NSString\* const kCDVAssetsLibraryPrefix;
extern NSString\* const kCDVFilesystemURLPrefix;

hope helpful and update soon.

**Comment by cuong-tran** [comment] 2016-06-08 11:40
I was able to pass this issue following Henray-Luo fix. Thanks.

**Comment by shazron** [comment] 2016-06-09 19:50
https://github.com/apache/cordova-plugin-file/blob/4270ae23b5ac9af9e3c9c18b6339d5bf9d0a6396/src/ios/CDVFile.h#L23-L24

**Comment by hollyschinsky** [comment] 2016-06-09 22:12
Hi guys!

Sorry for the delay on this, I've been away. I was able to reproduce this issue as well and it does appear to be all to do with what's changed in CocoaPods since version 0.39.0. The temp fix is to do as suggested above by @Henray-Luo.  You shouldn't need to specify any older versions of podspecs or do anything else to get around it. 

I've submitted [this PR](https://github.com/apache/cordova-plugin-file/pull/184) to the `cordova-plugin-file` repo to fix it permanently as well and will update the podspec to point to it once it's merged in. 

Thanks!
Holly

**Comment by hollyschinsky** [comment] 2016-06-09 22:22
Hi @revolunet! 

Regarding your earlier question about why Cordova and cordova-plugin-\* are not declared as a dependency of the "phonegap-ios-template" podspec, it's due to the fact that initially I didn't want to assume everyone creating an embedded webview project would want every plugin and didn't want to automatically include all that overhead. However, I later updated the project sample from a basic one to one that used all of the plugins in the `www`, so I guess it would make sense for this sample project since it requires them all at the moment. 

I think ultimately it could be helpful to have two versions of templates, one that is simply a barebones app that doesn't have all of those plugin requirements and another to include them all out of the box. Please let me know your thoughts on this though.. 

I'd also love to get some feedback on the types of projects that are being built using embedded webviews and anything else I could do to improve things. 

Thanks!
Holly

**Comment by hollyschinsky** [comment] 2016-06-10 20:44
The cordova-plugin-file fix has been merged in and I've published a [new podspec](https://cocoapods.org/pods/cordova-plugin-file) to use it. I also published [version 0.2.2](https://cocoapods.org/pods/phonegap-webview-ios/?q=phonegap) of this project which now works without any manual updates needed.

**Closed as completed by hollyschinsky** 2016-06-10 20:44 UTC

**Comment by revolunet** [comment] 2016-06-10 20:45
Awesome thanks Holly!

**Comment by revolunet** [comment] 2016-06-10 23:14
My goal currently is to be able to distribute a single Pod to 3rd party developers and this single pod would include all the necessary code and rules; (so cordova, plugins, resources and www folder).

We can imagine a command that could extract all the necessary files and create a .podspec from any working cordova project.

what do you think of this approach ?
